<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php
$subcategories = $this->getChildCategories();
?>
<?php $_helper    = $this->helper('Magento\Catalog\Helper\Output');?>
<?php if(count($subcategories)):?>
    <!--<div class="subcategory-list clearfix wrapper">-->
        <div class="subcategory list items subcategory-items">
            <?php foreach ($subcategories as $_category):?>
                <div class="category-item" style="background-image: url(<?php echo  $_category->getImageUrl();?>)">
                    <div class="item-inner-wrapper">
                        <a href="<?php echo $_category->getUrl();?>">
                            <div class="aside-category-name">
                                <span><?php echo $_category->getName();?></span>
                            </div>
                        </a>
                    </div>
                </div>
            <?php endforeach;?>
        <!--</div>-->
    </div>
<?php endif;?>
