<?php
/**
 * @author Rbofee Team
 * @copyright Copyright (c) 2018 Rbofee 
 * @package Rbofee_Base
 */
?>
<?php
/** @var \Rbofee\Base\Block\Adminhtml\Messages $block */
$messages = $block->getMessages();
?>
<?php if (!empty($messages)) : ?>
    <?php foreach ($messages as $message) : ?>
        <div class="messages rbobase-unsubscribe">
            <div class="message message-success success">
                <div data-ui-id="messages-message-success"><?= $message;?></div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
