
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>

<?php
$_helper    = $this->helper('Magento\Catalog\Helper\Output');
$_category  = $block->getCurrentCategory();
$_imgHtml   = '';
?>
<div class="catalog-category-title">

    <?php if ($_imgUrl = $_category->getImageUrl()) : ?>
        <?php
        $_imgHtml = '<div class="catalog-category-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($_category->getName()) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" /></div>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        /* @escapeNotVerified */ echo $_imgHtml;
        ?>
        <div class="rbo__puch__category-header-image">
            <h1><?php echo $_category->getName(); ?></h1>
        </div>
    <?php else: ?>
        <div class="rbo__puch__category-header">
            <h1><?php echo $_category->getName(); ?></h1>
        </div>
    <?php endif; ?>

</div>