<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
$mode = $block->getCurrentCategory()->getDisplayMode();
?>

<?php if (!$block->isContentMode() AND $mode != "SUBCATEGORY_MODE" || $block->isMixedMode()): ?>
        <?php echo $block->getProductListHtml() ?>
<?php endif; ?>
