<?php
/** @var $block \Magento\Catalog\Block\Category\View */

$category = $block->getCurrentCategory();
$children = $this->getCategoryChildren($category->getEntityId());
$_helper  = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php /*if($category->getDisplayMode() == ('SUBCATEGORY_MODE') || $category->getDisplayMode() == ('SUBCATEGORY_AND_PRODUCTS_MODE')):*/ ?>
<?php if(!empty($children)): ?>
<div class="rbo__puch__category">
    <ul class="rbo__puch__category-list">
        <?php foreach ($children as $child): ?>
            <li class="rbo__puch__category-item" style="background-image: url(<?= $block->getImageUrl($child);?>)">
                <a href="<?= $child->getUrl();?>">
                    <div class="catalog-subcategory-name">
                        <span><?= $child->getName();?></span>
                    </div>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

