<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$wishlistHelper = $objectManager->create('Magento\Wishlist\Helper\Data');

$itemsCollection = $wishlistHelper->getWishlist()->getItemCollection();

$productId = $block->getProduct()->getId();

$isInWishlist = false;
if($itemsCollection->getSize() > 0) {
    $itemsIds = $itemsCollection->getColumnValues('product_id');
    $isInWishlist = in_array($productId, $itemsIds) ? true : false;
}
?>
<?php if ($block->getWishlistHelper()->isAllow()): ?>
    <a href="#"
       class="action towishlist <?=$isInWishlist ? 'added' : ''?>"
       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
       data-action="add-to-wishlist"
       role="button">
        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
    </a>
<?php endif; ?>
