<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":false, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>
<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            if($(window).width() < 769) {
                var level0 = $('nav.navigation').find('li.level0');
                if(level0.length > 0) {
                    level0.each(function () {
                        var liElem = $(this).find('li.parent');
                        if(liElem.length > 0) {
                            liElem.each(function () {
                                $(this).addClass('has-children');
                            })
                        }
                    })
                }
            $('li.has-children > a').on('click', function () {
                hideOther($(this).parent());
                $(this).toggleClass('ui-state-active');
                $(this).parent().find('> ul.submenu').toggle();
                return false;
            })
            }
        });

        function hideOther(element){
            var hideEl = element.siblings('li.has-children');
            hideEl.each(function () {
                if($(this).find('a').hasClass('ui-state-active')){
                    $(this).find('a').removeClass('ui-state-active');
                    $(this).find('ul.submenu').hide();
                }
            })
        }
    });
</script>